name: Deploy to Azure

# Déclencheur : Quand on push sur la branche 'main'
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Se connecter à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Construire et Pousser l'image (Build & Push)
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./app
          push: true
          # Remplace 'gazoaal/lyricle' par ton image EXACTE
          tags: gazoaal/lyricle:latest 

      # 4. Déployer sur Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          # Remplace par le nom de ton App Service sur Azure (ex: lyricle-app-gazoaal)
          app-name: 'NOM_DE_TON_APP_AZURE' 
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'gazoaal/lyricle:latest'